osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

install:
- nvm install 6
- npm install -g yarn
- yarn install
before_script:
- npm run bootstrap
script:
- npm test
- $(npm bin)/lerna run test
after_success:
- test -n "$TRAVIS_TAG" && npm run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"