osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

before_script:
- npm run bootstrap
script:
- npm test
- $(npm bin)/lerna run test
after_success:
- npm run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"