version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install -g yarn
  - npm install -g cross-env
  - yarn install
  - npm run bootstrap

build_script:
  - node --version
  - npm --version
  - cross-env DEBUG=electron-builder npm run release

test: off