version: 0.4.{build}

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install -g yarn
  - npm install -g cross-env
  - npm install -g lerna-run
  - lerna-run yarn install
  - yarn install
  - ./node_modules/.bin/install-app-deps

build_script:
  - node --version
  - npm --version
  - cross-env DEBUG=electron-builder npm run release

test: off